WITH CUSTOMERORDER AS(
  SELECT C."customer_id" AS CUSTOMERID, C."full_name" AS CUSTOMERNAME, COUNT(O."order_id") AS NO_OF_ORDER
  FROM CUSTOMERS C
  JOIN ORDERS O ON C."customer_id"=O."customer_id"
  GROUP BY C."customer_id", CUSTOMERNAME
  ORDER BY NO_OF_ORDER DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, NO_OF_ORDER
FROM CUSTOMERORDER
